/*
 * Focused Ghidra closure: normal enemy object families.
 *
 * This is an address-annotated contract note, not a second guessed engine
 * implementation. The authoritative machine-readable rows are in
 * research/ghidra/normal-enemy-static-closure.json. The raw instruction
 * listing and C-like export are generated by
 * research/tools/run_player_external_closure.py with Ghidra's
 * x86:LE:16:Protected Mode language. No objdump output is used here.
 *
 * ES:DI is the pooled object record for every callback below. The scheduler
 * does not consume callback return flags; the callbacks may consume flags
 * returned by shared visibility, overlap, MAP, and animation helpers.
 * Consequently the direct player-write set is empty for all rows in this
 * closure. A callback can still affect later simulation by changing its
 * object callback, the shared effect table, or sound/effect globals.
 */

struct NormalEnemyObject /* offsets are DOS object-record offsets */ {
    s32 x_02_05;                 // +0x02 fixed-point X
    s32 y_06_09;                 // +0x06 fixed-point Y
    s32 velocity_x_0A_0D;        // +0x0A fixed-point X velocity
    s32 velocity_y_0E_11;        // +0x0E fixed-point Y velocity
    u16 sprite_slot_12;          // +0x12 logical BOB slot
    u16 callback_18;             // +0x18 callback offset; segment is +0x1C
    u16 animation_delay_1E;      // +0x1E/+0x20 timing word
    u32 animation_cursor_22;     // +0x22/+0x24 table cursor
    s8  orientation_28;          // +0x28 mirror/orientation byte
    s8  direction_29;            // +0x29 signed travel direction
    u16 phase_2A;                 // +0x2A phase/counter
    s8  source_or_kind_2C;        // +0x2C family-specific signed selector
    s16 timer_2D;                 // +0x2D countdown
    s8  map_blocked_2F;           // +0x2F MAP collision result
    u16 effect_cursor_30;         // +0x30 shared effect-table cursor
    s8  state_32;                 // +0x32 family state
    u16 phase_34;                 // +0x34 family phase where used
    s8  vertical_state_36;        // +0x36 FISCH/transition state where used
    s16 sine_or_probe_39;         // +0x39 family probe/phase where used
    s8  transition_state_3D;      // +0x3D FISCH/PENGO transition state
    s32 reserved_3E;              // +0x3E family timer/field where used
    u16 secondary_state_42;       // +0x42 UFO-only state
};

/* Shared callback contracts. */

// 01F7:1DCA: ES:DI object, CF=1 when outside the camera/visibility window.
// The callback branches to 01F7:1DEE on rejection; no player record is read.
extern bool object_visible_1DCA(NormalEnemyObject *object);

// 01F7:1DEE: clears object+0x18 and the ARE declaration high byte at
// FS:[object+0x1A+1]. It has no player write or callback return value.
extern void deactivate_object_1DEE(NormalEnemyObject *object);

// 01F7:1B77 and 01F7:1C4D/1C6E are shared object/player and MAP helpers.
// Their exact flags are preserved in the Ghidra listing; this note does not
// turn a flag into a C boolean where the original caller uses carry directly.
extern void object_player_range_1B77(/* register contract in ledger */);
extern bool map_block_probe_1C4D(/* register contract in ledger */);
extern bool map_raw_probe_1C6E(/* AX=y, BX=x; ZF from TEST 0x4000 */);

/* Initializers: all are far callbacks with ES:DI as the pooled object. */

// 01F7:70D9, wrappers 713D/714B -> callback 715E, PENGO 09/0A, W3.
void initialize_pengo_70D9(NormalEnemyObject *o) {
    o->callback_18 = 0x715E;
    o->phase_2A = 0;
    o->y_06_09 += 0x20;
    o->velocity_x_0A_0D = 0xFFFFA000;   // type 0A wrapper negates it
    o->velocity_y_0E_11 = 0xFFFD0000;
    o->effect_cursor_30 = 0;
    o->state_32 = 0;
    o->transition_state_3D = 0;
    o->reserved_3E = 0;
    o->phase_34 = 0;
    o->source_or_kind_2C = -1;
    o->timer_2D = 0x14;
    o->map_blocked_2F = -1;
}

// 01F7:771D, wrappers 776B/7779 -> callback 778C, KRABBE 07/08, W2.
void initialize_krabbe_771D(NormalEnemyObject *o) {
    o->callback_18 = 0x778C;
    o->phase_2A = 0;
    o->effect_cursor_30 = 0;
    o->y_06_09 += 0x20;
    o->direction_29 = -1; o->orientation_28 = -1;
    o->state_32 = 0;
    o->velocity_x_0A_0D = 0xFFFFB000;   // type 08 wrapper negates it
    o->source_or_kind_2C = -1;
    o->timer_2D = 0x14;
    o->map_blocked_2F = -1;
}

// 01F7:7AE3, wrappers 7B50/7B5E -> callback 7B71, FISCH 05/06, W2.
void initialize_fisch_7AE3(NormalEnemyObject *o) {
    o->callback_18 = 0x7B71;
    o->phase_2A = address_named_random_u16() >> 2;
    o->y_06_09 += 0x10;
    o->state_32 = 0;
    o->phase_34 = address_named_random_u16();
    o->velocity_x_0A_0D = 0xFFFF9000;   // type 06 wrapper negates it
    o->effect_cursor_30 = 0;
    o->sine_or_probe_39 = 0x14;
    o->vertical_state_36 = 0;
    o->source_or_kind_2C = -1;
    o->timer_2D = 0x19;
    o->map_blocked_2F = -1;
}

// 01F7:6651/6699 -> callback 66E1 -> 6757, SCHNEE 0B/0C, W3.
void initialize_schnee_6651(NormalEnemyObject *o) {
    o->callback_18 = 0x66E1;
    o->phase_2A = 0x14;
    o->y_06_09 += 0x20;
    o->direction_29 = -1; o->orientation_28 = -1;
    o->velocity_x_0A_0D = 0xFFFEB000;   // type 0C selects +0x15000
    o->source_or_kind_2C = -1;
    o->timer_2D = 0x14;
    o->map_blocked_2F = -1;
}

// 01F7:7E78, wrappers 7ED7/7EE5 -> callback 7EF8, FLIEGE 15/16, W4.
void initialize_fliege_7E78(NormalEnemyObject *o) {
    o->callback_18 = 0x7EF8;
    o->phase_2A = 0;
    o->phase_34 = 0;
    o->y_06_09 += 0x20;
    o->direction_29 = -1; o->orientation_28 = -1;
    o->velocity_x_0A_0D = 0xFFFE9000;   // type 16 wrapper negates it
    o->effect_cursor_30 = 0;
    o->state_32 = 0;
    o->source_or_kind_2C = -1;
    o->timer_2D = 0x14;
    o->map_blocked_2F = -1;
}

// 01F7:840D, wrappers 8451/845F -> callback 8472, SPINNE 17/18, W4.
void initialize_spinne_840D(NormalEnemyObject *o) {
    o->callback_18 = 0x8472;
    o->phase_2A = 0;
    o->effect_cursor_30 = 0;
    o->y_06_09 += 0x20;
    o->state_32 = 0;
    o->velocity_x_0A_0D = 0xFFFEE000;   // type 18 wrapper negates it
    o->source_or_kind_2C = -1;
    o->timer_2D = 0x14;
    o->map_blocked_2F = -1;
}

// 01F7:500C, wrappers 5050/505E -> callback 5071, BUGGY 19/1A, W5.
void initialize_buggy_500C(NormalEnemyObject *o) {
    o->callback_18 = 0x5071;
    o->phase_2A = 0;
    o->effect_cursor_30 = 0;
    o->y_06_09 += 0x20;
    o->state_32 = 0;
    o->velocity_x_0A_0D = 0xFFFEB000;   // type 1A wrapper negates it
    o->source_or_kind_2C = -1;
    o->timer_2D = 0x14;
    o->map_blocked_2F = -1;
}

// 01F7:5EAC, wrappers 5F07/5F15 -> callback 5F28, UFO 1B/1C, W5.
void initialize_ufo_enemy_5EAC(NormalEnemyObject *o) {
    o->callback_18 = 0x5F28;
    o->phase_2A = 0;
    o->effect_cursor_30 = 0;
    o->y_06_09 += 0x20;
    o->velocity_x_0A_0D = 0xFFFEB000;   // type 1C wrapper negates it
    o->state_32 = 0;
    o->secondary_state_42 = 0;
    o->source_or_kind_2C = -1;
    o->timer_2D = 0x14;
    o->map_blocked_2F = -1;
}

/* Callback state contracts, in original branch order. */

// 01F7:715E. Calls 1DCA first, then 1B77 and directional 1C4D/1C6E
// probes. +0x3D states 0..4 are the transition path; +0x32 states 0..4
// are patrol/fall. It integrates fixed-point X/Y, clamps velocity, records
// +0x2F, uses DS:6468/646C for phase reseed, scans DS:8806/8808, and routes
// the accepted persistent-player gate through 01F7:70C9 -> 4AB3.
void update_pengo_715E(NormalEnemyObject *o) {
    if (!object_visible_1DCA(o)) { deactivate_object_1DEE(o); return; }
    address_named_pengo_transition_and_patrol_state_machine(o);
    address_named_pengo_player_gate(o); // tail 70C9 -> 4AB3
}

// 01F7:778C. Same lifecycle ordering; directional probes use +0x39 and
// y offsets -1/-0x11/-0x0C. +0x32 states 0..3 and transition/sine fields
// drive movement. The player gate ends at 7AD3 -> 4BA0.
void update_krabbe_778C(NormalEnemyObject *o) {
    if (!object_visible_1DCA(o)) { deactivate_object_1DEE(o); return; }
    address_named_krabbe_state_machine(o);
    address_named_krabbe_player_gate(o); // tail 7AD3 -> 4BA0
}

// 01F7:7B71. Uses outer 10x20 probes, +0x39 and y offsets -1/-0x11/-0x0C;
// +0x36 states 0..3 and +0x3D states 0..4 are kept distinct. Direct writes
// are object fields only; the shared effect table is read and an accepted
// player gate reaches 4BA0 through 7AD3.
void update_fisch_7B71(NormalEnemyObject *o) {
    if (!object_visible_1DCA(o)) { deactivate_object_1DEE(o); return; }
    address_named_fisch_state_machine(o);
    address_named_fisch_player_gate(o); // tail 7AD3 -> 4BA0
}

// 01F7:66E1 -> 6757. The entry first checks DS:88AE and camera bounds
// (DS:81C0/81C4), then the MAP block and fixed-point patrol/fall path. The
// player-range branch has no 4AB3/4BA0 contact response in this family. The
// timed callback 6838 decrements +0x2A and clears the object at expiry.
void update_schnee_66E1_6757(NormalEnemyObject *o) {
    address_named_schnee_camera_gate_and_state_machine(o);
}

// 01F7:7EF8. Visibility/MAP probes use +/-0x20 and y offsets
// -1/-0x11/-0x0C. +0x32 states 0..8 contain patrol, vertical, and exit
// paths; the accepted player gate reaches 83FD -> 4AB3.
void update_fliege_7EF8(NormalEnemyObject *o) {
    if (!object_visible_1DCA(o)) { deactivate_object_1DEE(o); return; }
    address_named_fliege_state_machine(o);
    address_named_fliege_player_gate(o); // tail 83FD -> 4AB3
}

// 01F7:8472. +0x32 states 0..3, directional probes +/-0x23 and y offsets
// -1/-0x11/-0x0C. Phase reseed uses DS:6468/646C; contact tail 87C1 -> 4AB3.
void update_spinne_8472(NormalEnemyObject *o) {
    if (!object_visible_1DCA(o)) { deactivate_object_1DEE(o); return; }
    address_named_spinne_state_machine(o);
    address_named_spinne_player_gate(o); // tail 87C1 -> 4AB3
}

// 01F7:5071. +0x32 states 0..3, directional probes +/-0x28 and y offsets
// -1/-0x11/-0x0C. Phase reseed uses DS:6468/646C; contact tails 53E7/5911
// -> 4AB3.
void update_buggy_5071(NormalEnemyObject *o) {
    if (!object_visible_1DCA(o)) { deactivate_object_1DEE(o); return; }
    address_named_buggy_state_machine(o);
    address_named_buggy_player_gate(o); // tails 53E7/5911 -> 4AB3
}

// 01F7:5F28. +0x32 states 0..3 and +0x42 states 0..2; directional probes
// use +/-0x14 and y offsets -1/-0x11/-0x0C. The callback reads DS:81C4,
// DS:8806/8808, and DS:881A, may publish DS:612E=0x000D on its effect path,
// and routes its persistent-player tail through 6318 -> 4AB3.
void update_ufo_enemy_5F28(NormalEnemyObject *o) {
    address_named_ufo_enemy_state_machine(o);
}

/* Contact-tail contracts. */

// These tails perform the same object-side response publication: callback
// +0x18 becomes 4AB3 or 4BA0, +0x30 advances, then the shared response object
// is dispatched. They do not write the player record directly.
//
// 70C9 -> 4AB3     PENGO
// 6D4F -> 4AB3     BIENE (already in the player closure)
// 53E7 -> 4AB3     BUGGY
// 5911 -> 4AB3     BUGGY alternate branch
// 6318 -> 4AB3     UFO enemy
// 83FD -> 4AB3     FLIEGE
// 87C1 -> 4AB3     SPINNE
// 7AD3 -> 4BA0     FISCH/KRABBE

// The 4AB3/4BA0 -> 4C5D response and sound dispatch are already closed in
// the player external-state ledger; this closure stops there because the
// effect response cannot write player simulation during the same callback.

/* Static conclusions. */

// 1. Every callback has a shared visibility/removal edge and no direct player
//    write. The only persistent simulation feedback in this family is via
//    object lifetime, the shared effect table, or DS:612E/DS:6468 state.
// 2. The family-specific state machines are now exported with raw Ghidra
//    listings and independent A/B decompilation. Their exact runtime branch
//    frequencies and authored placements remain trace questions.
// 3. Native implementation may replace the current provisional hazard path
//    only after copying these object-field transitions and preserving the
//    scheduler's phase ordering. Player death must not be inferred from the
//    normal-enemy contact tails.
